print("Hello World!")
print("Hello Again")
print("I am typing this.")
print("This is fun.")
print('Yay! Printing!')
print("I'd much rather you 'not!'.")
print('I "said" do not touch this.')
print("Another Line")
